# Makefile for git-arborist development

# Load GH_TOKEN from .env for GitHub CLI targets
include .env


# =============================================================================
# TUI Dashboard
# =============================================================================
.PHONY: dashboard tui go-build

# Launch the worktree dashboard TUI
dashboard: go-build
	./bin/arborist

tui: dashboard

# Build the Go binary
go-build:
	@go build -o bin/arborist ./cmd/arborist

# =============================================================================
# Documentation Commands
# =============================================================================
.PHONY: ctags-report

# Generate a codebase report from ctags and save to docs/ctags-report.md
# Regenerates the tags file first, then produces a compact LLM-friendly report
# Usage: make ctags-report                  (compact, ~430 lines)
#        make ctags-report VERBOSE=1        (full detail, ~5k lines)
ctags-report:
	@./scripts/ctags-gen.sh
	@python3 scripts/ctags-report.py $(if $(VERBOSE),--verbose,) -o docs/ctags-report.md

# =============================================================================
# Git Commands
# =============================================================================
.PHONY: rebase-staging pr-summary fetch-pr-comments fetch-issue worktree

# Generate PR summary using Claude or Codex from git diff
# Usage: make pr-summary [branch=<branch-name>] [model=claude|codex]
# Examples:
#   make pr-summary                        - Diff against staging (default)
#   make pr-summary branch=main            - Diff against main
#   make pr-summary model=codex            - Use Codex for summary
pr-summary:
	@./scripts/pr-summary.sh $(if $(branch),--branch=$(branch)) $(if $(model),--model=$(model))

fetch-pr-comments:
	@./scripts/fetch-pr-comments.sh

# Fetch GitHub issue and launch Claude to analyze and implement
# ISSUE is optional, can be run with no args
fetch-issue:
	./scripts/fetch-issue.sh $(ISSUE)

# Rebase all local branches (except main and staging) onto staging
rebase-staging:
	@current_branch=$$(git branch --show-current); \
	for branch in $$(git branch --format='%(refname:short)' | grep -v -E '^(main|staging)$$'); do \
		echo "Rebasing $$branch onto staging..."; \
		git checkout $$branch && \
		git stash && \
		git pull && \
		git rebase staging || { echo "Failed to rebase $$branch"; git rebase --abort 2>/dev/null; } && \
		git stash pop; \
	done; \
	echo "Returning to original branch: $$current_branch"; \
	git checkout $$current_branch

worktree:
	./scripts/worktree.sh

wl:
	@echo "Current Git Worktrees:"
	@./scripts/worktree-list.sh


# =============================================================================
# Help
# =============================================================================
.PHONY: help

help:
	@echo "TUI Dashboard:"
	@echo "  make dashboard   - Build and launch the worktree dashboard TUI"
	@echo "  make tui         - Alias for dashboard"
	@echo "  make go-build    - Build the Go binary"
	@echo ""
	@echo "Documentation Commands:"
	@echo "  make ctags-report              - Generate codebase report to docs/ctags-report.md"
	@echo "  make ctags-report VERBOSE=1    - Generate verbose report (full detail)"
	@echo ""
	@echo "Git Commands:"
	@echo "  make pr-summary [branch=<name>] [model=claude|codex] - Generate PR summary"
	@echo "  make fetch-pr-comments         - Fetch PR comments generated by AI"
	@echo "  make fetch-issue ISSUE=<num>   - Fetch GitHub issue and launch Claude to implement"
	@echo "  make rebase-staging            - Rebase all local branches onto staging"
	@echo "  make worktree                  - Create a git worktree for the current branch"
	@echo "  make wl                        - List current git worktrees"

# =============================================================================
# GitHub CLI Commands
# =============================================================================
# Usage:
#   make issue list
#   make issue view 1
#   make issue create --title "Bug" --body "Details"
#   make pr list
#   make pr create --base staging
#   make pr view 42
# =============================================================================

# Capture extra arguments when "issue" or "pr" is the target
ifneq (,$(filter issue pr,$(firstword $(MAKECMDGOALS))))
  GH_ARGS := $(wordlist 2,$(words $(MAKECMDGOALS)),$(MAKECMDGOALS))
  $(eval $(GH_ARGS):;@:)
endif

.PHONY: issue pr

issue:
	GH_TOKEN=$(GH_TOKEN) gh issue $(GH_ARGS)

pr:
	GH_TOKEN=$(GH_TOKEN) gh pr $(GH_ARGS)
